/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#dce1ff",
        "surface-container": "#f1f5f9",
        "surface": "#ffffff",
        "on-primary-fixed-variant": "#0039b5",
        "on-tertiary": "#5a1c00",
        "on-secondary-container": "#23005c",
        "outline-variant": "#e2e8f0",
        "on-primary": "#ffffff",
        "surface-bright": "#ffffff",
        "secondary-container": "#e9ddff",
        "bg-light": "#F8FAFC",
        "on-error-container": "#410002",
        "surface-variant": "#f1f5f9",
        "on-tertiary-fixed-variant": "#7f2b00",
        "on-tertiary-container": "#370e00",
        "surface-container-low": "#f8fafc",
        "on-primary-fixed": "#001552",
        "inverse-surface": "#2e303a",
        "surface-dim": "#cbd5e1",
        "bg-dark": "#0D1117",
        "on-secondary-fixed-variant": "#5516be",
        "on-primary-container": "#001552",
        "tertiary-fixed": "#ffdbce",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e2e8f0",
        "primary-fixed-dim": "#b7c4ff",
        "tertiary": "#c64700",
        "inverse-primary": "#b7c4ff",
        "market-up": "#16a34a",
        "surface-tint": "#2e62ff",
        "outline": "#94a3b8",
        "market-ref": "#d97706",
        "secondary-fixed-dim": "#d0bcff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#ffdbce",
        "on-error": "#ffffff",
        "background": "#F8FAFC",
        "tertiary-fixed-dim": "#ffb599",
        "secondary-fixed": "#e9ddff",
        "primary": "#2e62ff",
        "error": "#ba1a1a",
        "secondary": "#571bc1",
        "on-surface": "#0f172a",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#23005c",
        "on-tertiary-fixed": "#370e00",
        "market-ceiling": "#c026d3",
        "on-surface-variant": "#475569",
        "inverse-on-surface": "#f1f5f9",
        "on-background": "#0f172a",
        "primary-fixed": "#dce1ff",
        "market-floor": "#d97706",
        "surface-container-highest": "#cbd5e1",
        "market-down": "#dc2626"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "24px",
        "card-gap": "12px",
        "gutter": "16px",
        "sidebar-width": "240px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "data-lg": ["JetBrains Mono"],
        "data-md": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "data-sm": ["JetBrains Mono"]
      },
      fontSize: {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "data-lg": ["18px", {"lineHeight": "24px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "data-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "data-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
