# -*- coding: utf-8 -*-
"""1_quickstart_stock_vietnam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_quickstart_stock_vietnam.ipynb

# Dữ liệu Chứng khoán Việt Nam

Hướng dẫn sử dụng **vnstock** để truy xuất dữ liệu thị trường chứng khoán Việt Nam toàn diện bao gồm:
- Danh sách mã chứng khoán và thông tin thị trường
- Dữ liệu giá lịch sử và thời gian thực
- Thông tin doanh nghiệp và báo cáo tài chính
- Thống kê giao dịch và phân tích thị trường

**⚡ Lựa chọn nền tảng:**
- **GitHub Codespaces** (Khuyến nghị): Môi trường đầy đủ, không cần cài đặt Python phức tạp và không bị chặn IP từ nguồn VCI.
- **Google Colab**: Miễn phí với hỗ trợ lưu trữ trong Google Drive. Hiện tại đang bị VCI chặn IP, cần dùng proxy.

**Lưu ý:** Nếu gặp vấn đề chặn IP từ nguồn VCI trên Colab, hãy thử [GitHub Codespaces](https://github.com/features/codespaces).

<p>
  <a href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_quickstart_stock_vietnam.ipynb" target="_blank" style="display:inline-block; vertical-align:middle; margin-left:8px;">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height:20px; vertical-align:middle;">
  </a>
  <a href="https://codespaces.new/thinh-vu/vnstock" target="_blank" style="display:inline-block; vertical-align:middle;">
    <img src="https://img.shields.io/badge/Open%20in-GitHub%20Codespaces-blue?logo=github" alt="Open in GitHub Codespaces" style="height:20px; vertical-align:middle;">
  </a>
</p>

## Mục lục

1. [Cài đặt & Thiết lập](#scrollTo=BJYQtG0B4-sq)
2. [Danh sách mã chứng khoán](#scrollTo=3Wh1-IOJ4-sr)
3. [Dữ liệu giá & Báo giá](#scrollTo=rdlN42Hl4-st)
4. [Thông tin doanh nghiệp](#scrollTo=fdN7Sobv4-sw)
5. [Báo cáo tài chính](#scrollTo=8r_laqBY4-sz)
6. [Giao dịch & Dữ liệu thị trường](#scrollTo=sz8ZmBjF4-sv)
7. [Bộ lọc cổ phiếu](#scrollTo=4hihIdQ74-sz)

**Nguồn dữ liệu:**
   - [KBS](https://kbbuddywts.kbsec.com.vn/) (Chứng khoán KB)
   - [VCI](https://trading.vietcap.com.vn/priceboard) (Chứng khoán Vietcap) >> Cần cài đặt vnstock trên máy tính cá nhân hoặc dịch vụ không thuộc Google Cloud để truy cập (do máy chủ VCI chặn dải IP từ Google)

<a id="installation"></a>
## I. Cài đặt & Thiết lập

### Cài đặt chuẩn
"""

# Cài đặt hoặc nâng cấp vnstock
!pip install -U vnstock

# Cài đặt từ mã nguồn Github
# !pip install git+https://github.com/thinh-vu/vnstock

"""### Xác thực người dùng

Phiên bản vnstock 3.4.0 bắt đầu hỗ trợ tính năng nhận diện người dùng miễn phí để mở khóa tính năng so với sử dụng theo chế độ khách.

- 🚀 Đăng ký API key để tăng giới hạn sử dụng:

    - Khách (Guest):
        - Phù hợp để thử nghiệm nhanh, xem thử tính năng. Quảng cáo hiện thường xuyên
        - 20 requests/phút - không cần đăng ký
        - Tải tối đa 4 kỳ báo cáo tài chính

    - Cộng đồng (Community):
        - Trải nghiệm tính năng thư viện, chưa muốn gắn bó. Quảng cáo hiện thường xuyên
        - 60 requests/phút - đăng ký miễn phí
        - Tải tối đa 8 kỳ báo cáo tài chính

    - Tài trợ (Sponsor):
        - Không quảng cáo
        - 3-5x số lượt requests/phút so với bản miễn phí.
        - Truy cập đầy đủ các kỳ báo cáo tài chính.
        - Ủng hộ dự án phát triển công cụ & cộng đồng

- 📌 Đăng nhập Google để tạo tài khoản và lấy API key miễn phí tại: https://vnstocks.com/login
"""

# Chạy lệnh và nhập API key theo hướng dẫn
from vnstock import register_user
register_user()
# hoặc nhập trực tiếp API key vào hàm register_user
# register_user('YOUR_API_KEY')

"""### Tải Vnstock Agent Guide

> Vnstock Agent Guide là bộ tài liệu hướng dẫn và tham chiếu cách sử dụng các thư viện trong hệ sinh thái Vnstock. Nhờ có Agent Guide, các công cụ AI Agent để viết code Python có thể hoạt động chính xác nhờ hướng dẫn và tham chiếu này - giúp bạn vibe coding tạo ra ứng dụng mình muốn mà không yêu cầu kiến thức kỹ thuật quá nhiều.
"""

# Bỏ dấu ! phía trươc nếu chạy code trong Terminal riêng

# 1. Tải về bộ hướng dẫn
!git clone https://github.com/vnstock-hq/vnstock-agent-guide.git

# 2. Sao chép vào dự án của bạn (Chọn lệnh phù hợp với OS)

# macOS / Linux:
!cp -r vnstock-agent-guide/docs vnstock-agent-guide/.agent vnstock-agent-guide/.cursor vnstock-agent-guide/.github vnstock-agent-guide/AGENTS.md vnstock-agent-guide/CLAUDE.md vnstock-agent-guide/GEMINI.md ./

"""Lệnh riêng cho Windows (PowerShell):

```
Copy-Item -Path vnstock-agent-guide/docs, vnstock-agent-guide/.agent, vnstock-agent-guide/.cursor, vnstock-agent-guide/.github, vnstock-agent-guide/AGENTS.md, vnstock-agent-guide/CLAUDE.md, vnstock-agent-guide/GEMINI.md -Destination ./ -Recurse -Force
```

Sau khi bộ tài liệu sẵn sàng trong môi trường làm việc, bạn có thể duyệt qua các file và thêm file vào ngữ cảnh chat để AI có thể hiểu cách viết code chính xác sử dụng thư viện Vnstock.

### Nạp thư viện

Bây giờ bạn có thể import và sử dụng vnstock bình thường:
"""

# Import các module của vnstock
from vnstock import Listing, Quote, Company, Finance, Trading

# Cách khác: Import từ nguồn dữ liệu cụ thể
# from vnstock.explorer.vci import Listing, Quote, Company, Finance, Trading
# from vnstock.explorer.tcbs import Quote, Company, Finance, Trading

print("✅ Tất cả modules đã được import thành công!")

"""<a id="listings"></a>
## II. Danh sách mã chứng khoán

Lấy danh sách các cổ phiếu giao dịch trên các sàn Việt Nam (HOSE, HNX, UPCOM).

### KBS

#### Listing: Liệt kê danh sách chứng khoán
"""

# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
from vnstock import Listing
listing = Listing(source='KBS')

"""#### Danh sách tất cả mã CK niêm yết (đơn giản)"""

listing.all_symbols()

"""#### Liệt kê mã CP theo sàn (đầy đủ)"""

# Dữ liệu bao gồm tất cả các mã không kể đang niêm yết hay không
listing.symbols_by_exchange()

"""#### Liệt kê mã CP theo ngành icb"""

listing.symbols_by_industries()

"""#### Danh sách cổ phiếu theo nhóm"""

# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
listing.symbols_by_group('VN30')

"""### VCI

#### Khởi tạo đối tượng
"""

from vnstock import Listing

# Khởi tạo đối tượng Listing với nguồn VCI
listing = Listing(source='VCI')

"""#### Danh sách tất cả mã cổ phiếu (Đơn giản)"""

# Lấy danh sách đơn giản tất cả mã chứng khoán
all_symbols = listing.all_symbols()
print(f"Tổng số mã: {len(all_symbols)}")
all_symbols.head(10)

"""#### Danh sách cổ phiếu theo sàn giao dịch (Đầy đủ)"""

# Lấy thông tin chi tiết cho tất cả mã theo sàn giao dịch
# Bao gồm cả mã đang và đã ngừng niêm yết
by_exchange = listing.symbols_by_exchange()
by_exchange.head()

"""#### Danh sách cổ phiếu theo nhóm"""

# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
listing.symbols_by_group('VN30')

"""#### Danh sách theo ngành (ICB)"""

# Lấy danh sách cổ phiếu được nhóm theo ngành ICB
by_industry = listing.symbols_by_industries()
by_industry.head()

"""#### Danh sách mã ngành theo mã icb"""

listing.industries_icb()

"""#### Danh sách mã hợp đồng tương lai"""

listing.all_future_indices()

"""#### Danh sách mã trái phiếu chính phủ"""

listing.all_government_bonds()

"""#### Danh sách bộ chỉ số"""

listing.all_indices()

"""## Quote: Giá chứng khoán

### KBS
"""

from vnstock import Quote
quote = Quote(symbol='ACB', source='KBS')

"""#### Giá lịch sử

##### Cổ phiếu
"""

# Lấy báo cáo lùi N ngày so với hiện tại (bao gồm cả ngày hiện tại)
df = quote.history(length='90', interval='d')
df

# Lấy báo cáo theo 1 dải thời gian cố định
df = quote.history(start='2024-01-01', end='2025-03-19', interval='d')
df

"""##### Hợp đồng tương lai"""

quote.history(symbol='VN30F1M', length=90, interval='d')

quote.history(symbol='41I1G2000', length=90, interval='d')

"""##### Chỉ số"""

quote.history(symbol='VNINDEX', length=90, interval='d')

quote.history(symbol='HNXINDEX', length=90, interval='d')

quote.history(symbol='UPCOMINDEX', length=90, interval='d')

"""##### Chứng quyền"""

quote.history(symbol='CFPT2314', length=90, interval='d')

"""##### Trái phiếu niêm yết"""

quote.history(symbol='CII424002', length=90, interval='d')

"""#### Intraday: dữ liệu khớp lệnh"""

# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
quote.intraday(symbol='ACB', page_size=10_000, show_log=False)

"""### VCI"""

from vnstock import Quote
quote = Quote(symbol='ACB', source='VCI')

"""#### Giá lịch sử

##### Cổ phiếu
"""

# Khung thời gian ngày: 1D hay d cho interval
df = quote.history(start='2024-01-01', end='2025-11-10', interval='d')
df

# Khung thời gian phút: 1m hoặc m cho interval
df = quote.history(start='2025-01-02', end='2025-11-10', interval='1m')
df

# Khung thời gian giờ: 1H hoặc h cho interval
df = quote.history(start='2025-01-02', end='2025-11-10', interval='h')
df

"""##### Hợp đồng tương lai"""

quote.history(symbol='VN30F1M', start='2024-01-02', end='2025-11-10', interval='1D')

quote.history(symbol='41I1FB000', start='2025-01-02', end='2025-11-10', interval='1m')

quote.history(symbol='VN30F2511', start='2025-01-02', end='2025-11-10', interval='1D')

"""##### Chỉ số"""

quote.history(symbol='VNINDEX', start='2024-01-02', end='2025-11-10', interval='1D')

quote.history(symbol='HNXINDEX', start='2024-01-02', end='2025-11-10', interval='1D')

quote.history(symbol='UPCOMINDEX', start='2024-01-02', end='2025-11-10', interval='1D')

"""##### Chứng quyền"""

quote.history(symbol='CFPT2314', start='2024-01-02', end='2025-11-10', interval='1D')

"""##### Trái phiếu niêm yết"""

quote.history(symbol='CII424002', start='2024-01-02', end='2025-11-10', interval='1D')

"""#### Intraday: dữ liệu khớp lệnh"""

# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
quote.intraday(symbol='ACB', page_size=10_000, show_log=False)

"""## Trading: Giao dịch

### Bảng giá

#### KBS
"""

from vnstock import Trading
trading = Trading(source='KBS')

trading.price_board(['ACB'])

trading.price_board(['VCB','ACB','TCB','BID']).T # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

"""#### VCI"""

from vnstock import Trading
trading = Trading(source='VCI')

trading.price_board(['ACB'])

trading.price_board(['VCB','ACB','TCB','BID']) # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

"""## Company: Thông tin công ty

### KBS

> Đã bổ sung nguồn dữ liệu từ VCI từ bản Vnstock 3.4.0
"""

from vnstock import Company
company = Company(symbol='ACB', source='KBS')

"""Loại bỏ đoạn mã `.head()` để xem toàn bộ dữ liệu thay vì chỉ lấy 5 dòng đầu tiên.

#### Hồ sơ
"""

company.overview()

"""#### Tỷ lệ sở hữu"""

company.ownership()

"""#### Cổ đông"""

company.shareholders()

"""#### Công ty con"""

company.subsidiaries()

"""#### Công ty liên kết"""

# Phương thức này không có trong nguồn TCBS
company.affiliate()

"""#### Lãnh đạo"""

company.officers(filter_by='working').head() # filter_by='all' hoặc 'working' hoặc 'resigned'

"""#### Lịch sử tăng vốn"""

company.capital_history()

"""#### Tin tức"""

company.news().head(3)

"""#### Sự kiện"""

company.events()

"""#### Giao dịch nội bộ"""

company.insider_trading()

"""### VCI

> Đã bổ sung nguồn dữ liệu từ VCI từ bản Vnstock 3.2.0
"""

from vnstock import Company
company = Company(symbol='ACB', source='VCI')

"""Loại bỏ đoạn mã `.head()` để xem toàn bộ dữ liệu thay vì chỉ lấy 5 dòng đầu tiên.

#### Hồ sơ
"""

company.overview()

"""#### Cổ đông"""

company.shareholders()

"""#### Công ty con"""

company.subsidiaries()

"""#### Công ty liên kết"""

# Phương thức này không có trong nguồn TCBS
company.affiliate()

"""#### Lãnh đạo"""

company.officers(filter_by='working').head() # filter_by='all' hoặc 'working' hoặc 'resigned'

"""#### Tin tức"""

company.news().head(3)

"""#### Sự kiện"""

company.events().head(3)

"""#### Báo cáo phân tích"""

company.reports()

"""#### Tình hình tài chính"""

company.ratio_summary()

"""#### Thống kê giao dịch"""

company.trading_stats()

"""## Finance: Báo cáo tài chính

### KBS
"""

from vnstock import Finance
finance = Finance(symbol='ACB', source='KBS')

"""#### Bảng cân đối kế toán"""

finance.balance_sheet(period='year')

finance.balance_sheet(period='quarter')

"""#### Báo cáo kết quả kinh doanh"""

finance.income_statement(period='year')

finance.income_statement(period='quarter')

"""#### Báo cáo lưu chuyển tiền tệ"""

finance.cash_flow(period='year')

finance.income_statement(period='quarter')

"""#### Chỉ số tài chính"""

finance.ratio(period='year')

finance.ratio(period='quarter')

"""### VCI"""

from vnstock import Finance
finance = Finance(symbol='ACB', source='VCI')

"""#### Bảng cân đối kế toán"""

finance.balance_sheet(period='year', lang='vi', dropna=True)

finance.balance_sheet(period='quarter', lang='en', dropna=True).head()

"""#### Báo cáo kết quả kinh doanh"""

finance.income_statement(period='year', lang='vi', dropna=True).head()

finance.income_statement(period='quarter', lang='en', dropna=True).head()

"""#### Báo cáo lưu chuyển tiền tệ"""

finance.cash_flow(period='year', dropna=True).head()

finance.income_statement(period='quarter', lang='en', dropna=True).head()

"""#### Chỉ số tài chính"""

finance.ratio(period='year', lang='vi', dropna=True).head()

finance.ratio(period='quarter', lang='en', dropna=True).head()